github:
  enabled: true
  repoURL: "https://github.com/Trident-Development/2024-new-grad-intern"
linkedIn:
  enabled: true
  timespan: "week"
  queries: 
    - "software engineer intern"
    - "backend engineer intern"
    - "embedded systems intern"
  desiredJobTitles: 
    - "intern"
    - "co-op"
  blacklistJobTitles:
    - "jr"
    - "junior"
    - "sr"
    - "senior"
    - "tech lead"
    - "market"
    - "sale"
    - "business"
    - "mechanical"
    - "benefit"
    - "inclusion"
    - "coordinator"
    - "clearing"
    - "electric"
    - "design"
    - "client"
    - "legal"
    - "tax"
    - "social"
    - "process"
  description:
    blacklistSubstrings: 
      - "unpaid"
    requiredSubstrings: ["interns"]
  locationsToQuery:
    - "United States"
    - "Remote"
    - "Boston"
    - "New York City"
    - "Austin"
    - "Dallas"
    - "Chicago"
    - "Boulder"
    - "Pittsburgh"
    - "McLean"
    - "Charlotte"
    - "California"
    - "Bay Area"
    - "San Francisco"
    - "Mountain View"
    - "Sunnyvale"
    - "Menlo Park"
    - "Palo Alto"
    - "San Mateo"
    - "Los Angeles"
    - "Santa Clara"
    - "Cupertino"
    - "San Diego"
    - "Novato"
    - "San Ramon"
    - "Irvine"
    - "Foster City"
    - "Newark"
    - "Fremont"
    - "Berkeley"
    - "Seattle"
    - "Bellevue"
    - "Redmond"
    - "Kirkland"